name: Deploy

on:
  push:
    banches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd unbot
            git pull
            docker compose -f docker-compose.yml -f docker-compose.prod.yml down
            TOKEN="${{ secrets.TOKEN }}" docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
